[package]
name = "dact"
version = "0.1.0"
authors = ["Pablo Barton <pablo.barton@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
csv = "1.1.6"
